--  RENEW DB
drop table BookActivity
drop table BookGenre
drop table BookMediaType
drop table History
drop table [Login]
drop table Publisher
drop table Series
drop table ShelfBook
drop table ShelfGenre
drop table UserGroups
drop table UserShelve
drop table [User]
drop table Genre
drop table MediaType
drop table Shelf
drop table Book
drop table Author
drop table Country
drop table [Language]
drop table [Group]